name: Publish dev
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Deps
        run: npm i

      - name: Install dependencies
        run: npm ci --ignore-scripts 

      - name: Build
        run: yarn build

      - name: Publish
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(git rev-parse --short HEAD).$(date +%s)
          npm publish --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
